//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recbox2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskMovy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KioskMovy()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int KioskMovieId { get; set; }
        public int KioskId { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> OnHand { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Kiosk Kiosk { get; set; }
        public virtual Movy Movy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
