//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recbox2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.KioskMovies = new HashSet<KioskMovy>();
            this.Rentals = new HashSet<Rental>();
        }
    
        public int MovieId { get; set; }
        public int GenreId { get; set; }
        public int RatingId { get; set; }
        public string Title { get; set; }
        public int Minutes { get; set; }
        public decimal Stars { get; set; }
        public string Description { get; set; }
        public string MovieImage { get; set; }
        public int Year { get; set; }
        public decimal Fee { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KioskMovy> KioskMovies { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
