//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recbox2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalId { get; set; }
        public int CustomerId { get; set; }
        public int KioskId { get; set; }
        public int MovieId { get; set; }
        public System.DateTime RentalDate { get; set; }
        public System.DateTime RentalDueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public decimal Fee { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Kiosk Kiosk { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
